### ISSUE TITLE
Change search bar text

### ISSUE THREAD

**Issue by razzius** [razzius/hms-weave#121]
Additional ask: Change search bar text from "Search" to "Click or type something and press enter." I think people don't know that free text searching is an option.

**Comment by jjchen20** [comment]
People may also not realize that they can search using multiple tags, i.e. Dermatology and Oncology, and filter using multiple options.

Instead of changing the search bar text, we could keep the "Search" text (especially after applying changes from #120 to the search function), and add static words underneath the filter boxes that says: "You may select one or more tags or filters."

**Comment by razzius** [comment]
Now that the search is much more intuitive with https://github.com/razzius/hms-weave/issues/124 and #127, I'm inclined to leave the text simply as "Search" and see if users can make sense of it in its current form. What do others think?

**Comment by jjchen20** [comment]
I'm in favor of having a comma or semi-colon generate the tag in the search bar. People might realize that they can make lists of tags and the search will triangulate on people who fit all tag criteria.

**Comment by razzius** [comment]
I think "Search" is a fine placeholder. Open to reconsidering; just reopen the issue and comment.

**Comment by jjchen20** [comment]
Unless the person has seen us demo the free text search on Weave or the
faculty is searching for their own tag, I haven't seen anyone do free text
search from the search bar. Most just scroll and click. We can revisit this
at a later point in time, but I think some explanation at the bottom that
mentions people can search for tags or do free text search would be
helpful. A description could be grayed out text at the bottom of the
sort/filter options.
