### ISSUE TITLE
Student registration routes to faculty privileges

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#22]
A pretty big error just came up for me. I registered as a student, got the mentee confirmation email, but it routed me to the faculty page with the video tutorial and I have faculty privileges even though I clicked "find a mentor" under the students button.

**Comment by jjchen20** [comment]
Let's check on this closer to student roll out.

**Comment by jjchen20** [comment]
A few student logins have routed to faculty privileges.

One student who registered got this screen on login:

![image](https://user-images.githubusercontent.com/43801169/55695993-058c8e80-5989-11e9-902c-70090fd75250.png)

Student login should route to student privileges only, and faculty login should route to faculty privileges only.

**Comment by razzius** [comment]
Definitely see how this could happen. The top right of the screen says "login", so the client thinks they are not logged in, however their logged in state didn't clear when they logged out, probably because their session timed out rather than having them click the logout button. The client can detect a partial logout and clear its state to resolve this. I'll look into this

**Comment by jjchen20** [comment]
The session playback showed the student going back to the registration page several times, perhaps confused why the homepage routed to a faculty portal with a positive "availability for mentoring" toggle in the upper right hand corner.

**Comment by razzius** [comment]
As discussed in person, we don't have the indication this is a live issue. Closing.
