### ISSUE TITLE
Email address column

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#57]
Can we make the column width just a tad longer to accommodate an extra u here?
![image](https://user-images.githubusercontent.com/43801169/51097169-09e14b00-1790-11e9-84b4-8306f2168d1d.png)

**Comment by jjchen20** [comment]
If possible, it would really look better if the font could be smaller to accommodate the emails on one line. It doesn't look great on two lines.
![image](https://user-images.githubusercontent.com/43801169/51097207-4a40c900-1790-11e9-8edc-47db26598469.png)

**Comment by razzius** [comment]
@jjchen20 Could you test to see this is still an issue, and if so, add some more steps as to how to reproduce the issue? I'm not sure where this would be happening based on your screenshots.

**Comment by jjchen20** [comment]
@razzius This is still an issue. For faculty with long email addresses, the email truncates mid-word before continuing to the next line. It'd be aesthetically more pleasing to either have the email address all on one line with smaller font, or with words ending in naturally occurring breaks before going to the next line. For privacy reasons, I'm not including screenshots of full emails here. I'll send it to you separately.

**Comment by razzius** [comment]
One technically-simple approach is to let the browser put hyphens when emails are too long

![image](https://user-images.githubusercontent.com/2244895/56075510-c2f7f700-5d78-11e9-8c61-32f1582667c1.png)

A more robust approach here would be to move the email to the right-side panel so that it has more room. The left side with the profile image is only meant to be a few hundred pixels wide so it's questionable that the email is even there.

Yet another approach, as you mentioned, is to lower the font - this, however, would also be visually unappealing as there would then be different font sizes in different parts of the profile. It's possible to pull this off, but I'm not a typographer...

**Comment by razzius** [comment]
Turns out it's technically not bad to have word breaks at the @ sign (but only as necessary. If it fits in one line, no line break)

![image](https://user-images.githubusercontent.com/2244895/56075643-a78deb80-5d7a-11e9-8861-d12f528d1354.png)

I'd be happy to go with that (similarly it'd be easy to do the word break after the @)

**Comment by jjchen20** [comment]
I like the word break before the @ sign (as above) for the really long emails.

**Comment by razzius** [comment]
Deployed
