### ISSUE TITLE
Admin - Add degree columns to faculty in back end

### ISSUE THREAD

**Issue by JonKusner** [razzius/hms-weave#75]

**Comment by jjchen20** [comment]
To complete after #72 , in conjunction with #73

**Comment by jjchen20** [comment]
Time permitting (I know you said no to building this right now), this would be a good feature because the view provided in the browse all faculty view does not show any of the degrees. Jon and I will manually go through all of the profiles currently on Weave to add the degrees in the coming days/ week prior to dental faculty roll-out. But we can't do that for any of the profiles that are "unavailable" for mentoring. For referencing degrees in the future, it would be time consuming to click into each profile to see the degrees from a global standpoint. Ideally we'd be able to download a CSV file of all fields available in each profile.

**Comment by razzius** [comment]
![image](https://user-images.githubusercontent.com/2244895/72791137-a92eee80-3beb-11ea-8734-e600ded6233f.png)

Implemented degrees and all other tag fields in admin.

**Comment by jjchen20** [comment]
This looks great!
