### ISSUE TITLE
Email user domains

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#80]
Determine corresponding emails for these hospital affiliations:
![image](https://user-images.githubusercontent.com/43801169/53592211-c8e89e80-3b63-11e9-9098-75fbc131ab93.png)

![image](https://user-images.githubusercontent.com/43801169/53592256-dd2c9b80-3b63-11e9-9327-d8e4f932d281.png)

Add as allowable users once email addresses are confirmed.

**Comment by JonKusner** [comment]
https://docs.google.com/spreadsheets/d/1wV88rE4_zt8iS4JruhF7CkI5hZzHLx_ItA73Ib94ZjA/edit?usp=sharing

I have looked at all of the HMS affiliated institutions; this has grown since our last update. We need to update two things 1. Our list of preset institutions 2. the email domains that we are inclusive of.

1. Bolded are ones that we don't currently include in our preset list

Beth Israel Deaconess Medical Center
Boston Children’s Hospital
Brigham and Women’s Hospital
**Broad Institute**
Cambridge Health Alliance
Dana-Farber Cancer Institute
Forsyth Institute
Harvard Pilgrim Health Care
Hebrew SeniorLife
Joslin Diabetes Center
Judge Baker Children’s Center
Massachusetts Eye and Ear Infirmary
Massachusetts General Hospital
McLean Hospital
Mount Auburn Hospital
Schepens Eye Research Institute
Spaulding Rehabilitation Hospital
Veterans Affairs Boston Healthcare System
**Wyss Institute**


2. the email domains that we still need to include: **Broad Institute**, _Forsyth_, _Hebrew Senior Life_, **Judge Baker Children's Center**, McLean Hospital, Schepens Eye Research Institute, Spaulding Rehabilitation Hospital, **Wyss institute**.

The bolded ones are the ones that we can find and add. The unbolded institutions have emails that are under partners or something else. The italic I don't know.

Atrius Health | @atriushealth.org
Beth Israel Deaconess Medical Center | @bidmc.harvard.edu
Boston Children’s Hospital | @childrens.harvard.edu
Brigham and Women’s Hospital | @bwh.harvard.edu
Broad Institute |  
Cambridge Health Alliance | @challiance.org
Dana-Farber Cancer Institute | @dfci.harvard.edu
Forsyth Institute |  
Harvard Medical School | @hms.harvard.edu
Harvard Pilgrim Health Care | @hphc.org
Harvard School of Dental Medicine | @hsdm.harvard.edu
Hebrew SeniorLife |  
Joslin Diabetes Center | @joslin.harvard.edu
Judge Baker Children’s Center |  
Massachusetts Eye and Ear Infirmary | @meei.harvard.edu
Massachusetts General Hospital | @mgh.harvard.edu
McLean Hospital |  
Mount Auburn Hospital | @mah.harvard.edu
Partners Healthcare | @partners.org
Schepens Eye Research Institute |  
Spaulding Rehabilitation Hospital |  
Veterans Affairs Boston Healthcare System | @va.gov
Wyss Institute |

**Comment by jjchen20** [comment]
I can confirm that email addresses for all of the ones except the ones that are missing above are already allowable in the system and added to the Help page. I just added @joslin.harvard.edu to the Help page this afternoon.

**Comment by jjchen20** [comment]
Wyss Institute | @wyss.harvard.edu
Judge Baker Children’s Center | @jbcc.harvard.edu
Broad Institute | @broadinstitute.org

**Comment by jjchen20** [comment]
Forsyth Institute |  @forsyth.org
McLean Hospital |  @partners.org (already an allowable email domain)

**Comment by razzius** [comment]
Added 4 new domains in fffdccb0904882eaefb9e4b232f453d3ded57c13

```
+  "@broadinstitute.org",
+  "@forsyth.org",
+  "@jbcc.harvard.edu",
+  "@wyss.harvard.edu"
```
